#!/bin/bash
#logfile=/tmp/fwall.out.$$
curl -GET -k -u "Q+JgJOBrVTn1CarvSHrZQZwnaS9DSdW6xzpxD2yzP9jt+JSI0deLKDt11BFD02oWWdPVGcUkloe3D22s":"C/V8dsCYBiX+ZGrcinDHwt6PrZKeVQdoxatLokFs6h+IK1S9Zp/e9/ScrQwy3bnlFlBylCV2XQIa5PL+"  http://172.27.201.254/api/diagnostics/firewall/log | jq -j --arg ifname igb0 --arg ifname2 igb0_vlan169 '.[] | select(.interface==$ifname or .interface==$ifname2) | .interface, ",", .dir, ",", .__timestamp__, ",", .src,":",.srcport, ",", .dst,":",.dstport, ",", .protoname, ",", .label, "\n"' | column -t -s ","



